---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-db-migrations
  labels:
    app: stock-db-migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-db-migrations
  template:
    metadata:
      labels:
        app: stock-db-migrations
    spec:
      containers:
      - name: stock-db-migrations
        image: stock-db-migrations:latest
        ports:
        - containerPort: 8080
