---
apiVersion: v1
kind: Service
metadata:
  name: stock-db-migrations
spec:
  type: ClusterIP
  selector:
    app: stock-db-migrations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
